### ISSUE TITLE
Erro in /withdraw and /tip

### ISSUE THREAD

**Issue by LightBurdenOfficial** [samgos/reddbot-telegram#2]
I used this tutorial to perform the bot: https://github.com/DigitalCoin1/TipBot_SperoCoin

I am having problems with this bot in the / spero_tip and / spero_withdraw functions only.
The errors I receive are as follows:

>     /spero_tip @user
>     telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
>     Traceback (most recent call last):
>     File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/dispatcher.py", line 301, in process_update
>     handler.handle_update(update, self)
>     File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/commandhandler.py", line 173, in handle_update
>     return self.callback(dispatcher.bot, update, **optional_args)
>     File "command.py", line 54, in spero_tip
>     amount = float(amount)
>     ValueError: could not convert string to float: '@francissantana'

>     /spero_withdraw
> 
>     telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
>     Traceback (most recent call last):
>     File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/dispatcher.py", line 301, in process_update
>     handler.handle_update(update, self)
>     File "/usr/local/lib/python3.5/dist-packages/python_telegram_bot-11.1.0-py3.5.egg/telegram/ext/commandhandler.py", line 173, in handle_update
>     return self.callback(dispatcher.bot, update, **optional_args)
>     File "command.py", line 90, in spero_withdraw
>     amount = float(target)
>     ValueError: could not convert string to float: 'rZav53UV5gaV69PKkqUjaBqPz 0.01'

### Configuration

Google Cloud Engine + Ubuntu 16.04

Version of Python, python-telegram-bot & dependencies:

>     $ python3 -m telegram
>     python-telegram-bot 11.1.0
>     certifi 2018.08.24
>     future 0.16.0
>     Python 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]

**Comment by MetroCoin19** [comment]
hi did you ever fix this? im having errors doing /balance /withdraw and /tip 

```
`/balance 
2019-02-04 10:28:42,904 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "command.py", line 69, in balance
    soup = BeautifulSoup(quote_page.content, 'html.parser', parse_only=strainer)
NameError: name 'quote_page' is not defined
```




```
/withdraw 
error: {"code":-1,"message":"Accounting API is deprecated and will be removed in future.\nIt can easily result in negative or odd balances if misused or misunderstood, which has happened in the field.
\nIf you still want to enable it, add to your config file enableaccounts=1\n"}
2019-02-04 10:31:22,779 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "command.py", line 117, in withdraw
    balance = float(clean)
ValueError: could not convert string to float:
```





`/tip
2019-02-04 10:33:27,409 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "command.py", line 40, in tip
    amount =  target.split(" ")[1]
IndexError: list index out of range`
```

**Comment by MetroCoin19** [comment]
hi did you ever fix this? im also having problems.

`/balance 
2019-02-04 10:28:42,904 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "command.py", line 69, in balance
    soup = BeautifulSoup(quote_page.content, 'html.parser', parse_only=strainer)
NameError: name 'quote_page' is not defined




/withdraw 
error: {"code":-1,"message":"Accounting API is deprecated and will be removed in future.\nIt can easily result in negative or odd balances if misused or misunderstood, which has happened in the field.
\nIf you still want to enable it, add to your config file enableaccounts=1\n"}
2019-02-04 10:31:22,779 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "command.py", line 117, in withdraw
    balance = float(clean)
ValueError: could not convert string to float:




/tip
2019-02-04 10:33:27,409 - telegram.ext.dispatcher - ERROR - An uncaught error was raised while processing the update
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.5/dist-packages/telegram/ext/commandhandler.py", line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "command.py", line 40, in tip
    amount =  target.split(" ")[1]
IndexError: list index out of range`

**Comment by 7h3v01c3** [comment]
Hey guys these errors you are receiving is because the format is not being followed.

Either data was missing when the user called the command /tip /withdraw or the user put string data where float data was expected.

ie
they just called the command /tip no user and or no amount or /tip @user $1 or /tip @user one.  So
missing data or string data is the cause of those problems.  The same with /withdraw - 

You will see these errors in the backend when the user did not follow your instructions. These are not errors within the code.

Anyway best wishes and dig through the code some more you guys will figure it out.
